name: aventuris_app
description: "An RPG companion app for Aventuris."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI e ícones
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1

  # HTTP Requests
  dio: ^5.4.3

  # JSON (serialização e utilitários)
  intl: ^0.20.2

  # Gerenciamento de estado local (opcional se quiser usar também)
  shared_preferences: ^2.2.3

  go_router: ^15.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/